### ISSUE TITLE
Ticket with attachment throws fatal error

### ISSUE THREAD

**Issue by SoulGit** [clonemeagain/attachment_preview#64]
Upon trying to open a ticket that I have been working on successfully for about a week now, the below error is thrown. This doesn't occur on all tickets with attachments. Disabling inline preview plugin allows me to open the ticket and from here I can open click on all attachments successfully (so they aren't missing or corrupt). No system updates or reconfigurations. I just had this ticket open a few days ago without issue. Any pointers to troubleshoot further or resolve? 1.18 latest.  Thanks!

Fatal error: Uncaught TypeError: Unsupported operand types: string * int in phar:///var/www/html/osTicket/include/plugins/attachment_preview.phar/class.AttachmentPreviewPlugin.php:208 Stack trace: #0 phar:///var/www/html/osTicket/include/plugins/attachment_preview.phar/class.AttachmentPreviewPlugin.php(217): AttachmentPreviewPlugin->{closure}() #1 phar:///var/www/html/osTicket/include/plugins/attachment_preview.phar/class.AttachmentPreviewPlugin.php(281): AttachmentPreviewPlugin->unFormatSize() #2 phar:///var/www/html/osTicket/include/plugins/attachment_preview.phar/class.AttachmentPreviewPlugin.php(147): AttachmentPreviewPlugin->inlineAttachments() #3 phar:///var/www/html/osTicket/include/plugins/attachment_preview.phar/class.AttachmentPreviewPlugin.php(131): AttachmentPreviewPlugin::shutdownHandler() #4 [internal function]: AttachmentPreviewPlugin->{closure}() #5 {main} thrown in phar:///var/www/html/osTicket/include/plugins/attachment_preview.phar/class.AttachmentPreviewPlugin.php on line 208

**Comment by clonemeagain** [comment]
The plugin has been updated to be a phar, which has been tested with 1.18.
